[김성규] ADD: 상품 DetailView 기능 구현
wecode-bootcamp-korea/21-2nd-GanadaBang-backend pull request #3
Opened 2021-06-24 11:47 UTC by castleq90

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 상세페이지 기능 구현
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
작성한 코드에 select_related()를 사용해야 할까요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-25 01:31 UTC, lordmyshepherd requested changes

2021-06-25 01:31 UTC, lordmyshepherd commented on api/rooms/views/detail.py
> +class RoomDetailView(View):
Detail page 보다는 `Room`가 더 깔끔해보이는데 어떤가요? ㅎㅎ

```suggestion
class RoomView(View):
```

2021-06-25 01:31 UTC, lordmyshepherd commented on api/rooms/views/detail.py
> +
빈 줄은 지워주세요~

2021-06-25 01:31 UTC, lordmyshepherd commented on api/rooms/views/detail.py
> +        room   = Room.objects.get(id=room_id)
성규님 이제 View는 아주 잘 작성하시는군요!! 👍 

그럼 이제는 코드에 향기를 더하기 위해서 지금 작성하신 코드의 성능을 측정해보고 `select_related()` 또는 `prefetch_related()` method를 활용해서 database에 조회하는 회수를 줄여볼까요?

먼저 해당 코드가 실행될 때 얼마나 많은 쿼리가 DB에 조회되는지, LOGGING을 통해서 알 수 있습니다.
**settings.py에 아래 내용을 추가해주세요~**
다양한 Django Logging 정보는 https://docs.djangoproject.com/en/3.2/topics/logging/#topic-logging-parts-loggers를 참고해주세요~

```python


LOGGING = {
    'disable_existing_loggers': False,
    'version': 1,
    'formatters': {
         'verbose': {
            'format': '{asctime} {levelname} {message}',
            'style': '{'
        },
    },
    'handlers': {
        'console': {
            'class'     : 'logging.StreamHandler',
            'formatter' : 'verbose',
            'level'     : 'DEBUG',
        },
        'file': {
            'level'     : 'DEBUG',
            'class'     : 'logging.FileHandler',
            'formatter' : 'verbose',
            'filename'  : 'debug.log',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers' : ['console','file'],
            'level'    : 'DEBUG',
            'propagate': False,
        },
    },
}

```

2021-06-25 01:38 UTC, castleq90 commented on api/rooms/views/detail.py
> +class RoomDetailView(View):
그런것 같아요 ㅎㅎㅎ 수정하도록 하겠습니다 !

2021-06-25 01:40 UTC, castleq90 commented on api/rooms/views/detail.py
> +
빈 줄 지웠습니다 !

2021-06-25 01:44 UTC, castleq90 commented on api/rooms/views/detail.py
> +        room   = Room.objects.get(id=room_id)
settings.py에 위의 코드 추가 하였고 첨부해주신 문서 참고하여 `select_related()`혹은 `prefetch_related()`를 적용 해보도록 하겠습니다 !

2021-06-28 07:19 UTC, lordmyshepherd requested changes

2021-06-28 07:19 UTC, lordmyshepherd commented on api/rooms/views/detail.py
> +            ).get(id=room_id)
```suggestion
        room = Room.objects\
            .select_related('location','room_type','trade_type')\
            .prefetch_related('roomimage_set', 
                Prefetch(
                    'option', 
                    queryset = Option.objects.filter(option_type__id = 1),
                    to_attr='normal_options'
                ),
                Prefetch(
                    'option', 
                    queryset = Option.objects.filter(option_type__id = 2),
                    to_attr='security_options'
                )
            ).get(id=room_id)
```

2021-06-28 09:20 UTC, lordmyshepherd reviewed
성규님! 오프라인에서 코멘트 드린데로 수정해서 올려주세요~

2021-06-28 22:38 UTC, lordmyshepherd approved these changes

2021-06-28 22:38 UTC, lordmyshepherd commented on api/rooms/tests/test_detail.py
> +        ])
`bulk_insert` 👍

2021-06-28 22:38 UTC, lordmyshepherd commented on api/rooms/tests/test_detail.py
> +        a.created_at = '2021-06-28T19:50:19.403'
생성할때, created_at을 추가할 수 없나요??

```suggestion
        a = Room.objects.create(id='1',title='원룸1',content='매물정보 원룸 1 풀옵션 ',
                        location_id='1',room_type_id='1',trade_type_id='1',monthly_rent='30',
                        deposit='100',sale='0',agent='성규부동산',floor='1',room_area='10.12',
                        room_count='1',bathroom_count='1',heating_type='개별',elevator='유', created_at = '2021-06-28T19:50:19.403')
```

2021-06-28 22:39 UTC, lordmyshepherd commented
LGTM 👍  성규님!! 정말 고생 많으셨어요!!

2021-06-28 22:39 UTC, merged

2021-06-29 01:46 UTC, castleq90 commented on api/rooms/tests/test_detail.py
> +        a.created_at = '2021-06-28T19:50:19.403'
생성할때 추가하는 방식으로 해보았는데 ! `created_at = models.DateTimeField(auto_now_add=True)` 자동으로 생성 날짜가 생겨서 오류가 나는것 같아요 !