[이아란] Add: 메인페이지 랜덤리스트 구현
wecode-bootcamp-korea/21-2nd-GanadaBang-backend pull request #4
Opened 2021-06-25 03:37 UTC by araaaaan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 메인 4개 상품 정보 보여주기 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 프론트에서 값을 받아오지 않고 기본값을 설정해놓고 구현했습니다 , 값을 받지 않고 하는 다른 방법이 있을까요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-25 06:16 UTC, lordmyshepherd requested changes

2021-06-25 06:16 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +                            .filter(monthly_rent__lte=50).order_by('?')[:4]
여기서 `50`이라는 숫자와 `4`는 무엇을 의미하는지 알 수 있을까요??

2021-06-25 06:16 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +        rooms = Room.objects.select_related('location','room_type','trade_type')\
`select_related`와 `prefetch_related`를 사용하셨군요!! 👍👍
코드가 정말 깔끔하네요~~

2021-06-25 10:19 UTC, araaaaan commented on api/rooms/views/main.py
> +        rooms = Room.objects.select_related('location','room_type','trade_type')\
감사합니다... 하지만 바꾸겠습니다~~!!!

2021-06-25 10:19 UTC, araaaaan commented on api/rooms/views/main.py
> +                            .filter(monthly_rent__lte=50).order_by('?')[:4]
수정해서 올리겠습니다

2021-06-25 23:51 UTC, lordmyshepherd requested changes

2021-06-25 23:51 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            limit        = int(request.GET.get('limit', 1))
잘 수정해주셨네요~ 👍

2021-06-25 23:51 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +                    .order_by('?')[offset:offset+limit]
`filter()`는 `prefetch_related()` 앞에 붙여주는게 좋습니다!
`select_related`는 `JOIN` query를 사용한다고 했었죠?
filter는 select_related query시 WHERE 절이 붙어서 같이 조회됩니다!

`prefetch_related`는 추가로 쿼리를 날리기 때문에 filter 뒤에 붙여주는 것이 좋습니다!

```suggestion
            rooms = Room.objects.select_related('location','room_type','trade_type')\
                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
                    .prefetch_related('roomimage_set')\
                    .order_by('?')[offset:offset+limit]
```

2021-06-25 23:51 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
dong과 city를 서울로 필터링 하는 건가요?
```suggestion
                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
```

2021-06-25 23:51 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            limit        = int(request.GET.get('limit', 1))
아래 마이너한 내용 관련해서 피드백 남겼습니다~

2021-06-26 08:16 UTC, araaaaan commented on api/rooms/views/main.py
> +                    .order_by('?')[offset:offset+limit]
넵 이해했습니다!

2021-06-26 08:17 UTC, araaaaan commented on api/rooms/views/main.py
> +                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
서울 붙인건 ... default인줄 알았는데...좀 더 알아보겠습니다~

2021-06-26 08:40 UTC, araaaaan commented on api/rooms/views/main.py
> +                    .order_by('?')[offset:offset+limit]
검색하는 기능이 아니라서 keyword_sort의 범위는 dong으로 하나만 있으면 될거 같아서 다시 수정했습니다 혹시 여러개 넣으면 이점이 있을까요? 프론트에서 시,동 아무거나 넣어도 다 검색된다...? 이런 걸까요...?

2021-06-28 01:33 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
아란님 맞아요!! .get('key_word', default) 호출했을 때, 해당 key 값이 없으면 2번째 인자로 넣어준 값이 default로 반환됩니다!
제가 궁굼했던 건 filter를 dong, city를 둘다 서울로 하는 것 같아서 여쭤봤어요!!

`dong` 데이터에도 `서울`이라는 키워드가 포함되어 있는 건가요?

2021-06-28 01:37 UTC, araaaaan commented on api/rooms/views/main.py
> +                    .filter(Q(location__dong__icontains=keyword_sort) | Q(location__city__icontains=keyword_sort))\
아니요 dong에는 동만... 기준이 필요하겠군요 !!! 무슨말씀인지 알거같아요!

2021-06-28 01:39 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +                    .order_by('?')[offset:offset+limit]
아래에 답변 남겨 놓았습니다~

2021-06-30 02:25 UTC, lordmyshepherd requested changes

2021-06-30 02:25 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            }for room in rooms]
마이너한 리뷰인데 한칸 띄워주세요~
```suggestion
            } for room in rooms]
```

2021-06-30 02:25 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            return JsonResponse({'result':result}, status=200)
line 34와 35 사이에 한칸 띄워주세요~

2021-06-30 02:25 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +class RoomSuggestionView(View):
코드와 테스트코드 전부 깔끔하네요! 👍

2021-06-30 04:52 UTC, lordmyshepherd approved these changes

2021-06-30 04:52 UTC, lordmyshepherd commented
LGTM 👍 👍

2021-06-30 04:53 UTC, merged