[이아란] Add:주소 검색 API 기능 구현
wecode-bootcamp-korea/21-2nd-GanadaBang-backend pull request #5
Opened 2021-06-27 11:45 UTC by araaaaan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 오픈 API(주소검색) 사용하여 주소 검색기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-만약 검색기록을 보여주고 싶으면 들어온 주소검색 키워드 값을 빈 리스트에 넣어서 저장하고 프론트로 보내주면 되는 걸까요...? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-28 02:01 UTC, lordmyshepherd requested changes
추가로 테스트코드 작성해주세요~

2021-06-28 02:01 UTC, lordmyshepherd commented on ganadabang/settings.py
> +API_KEY    = API_KEY
어떤 API KEY인지 명확히 만들어주면 좋을 것 같아요!

2021-06-28 02:01 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            search_address = search_address.strip()
`strip`을 사용하시는 이유가 있나요?
```suggestion
            search_address = search_address.strip()
```

2021-06-28 02:01 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
아래와 같이 가독성을 위해서 아래와 같이 수정해보면 어떨까요?

```suggestion
            if len(search_address) < 2 : 
                    return JsonResponse({'message':'ADDRESS_IS_TOO_SHORT'}, status=400)
                    
            response = requests.get(f'http://api.vworld.kr/req/search? 
                service = search & 
                request = search & 
                version = 2.0 &
                crs     = EPSG:900913 &
                size    = 100 &
                page    = 1 &
                query   = {address} & 
                type    = {type} &
                category = {category} &
                format   = json &
                errorformat = json & 
                key = {API_KEY}'
            )
                
            search_data = response.json()
            
            return JsonResponse({'message': 'SUCCESS', 'search_data': search_data}, status=200)
            
        except KeyError:
            return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
```

2021-06-28 02:01 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            response= requests.get(f'http://api.vworld.kr/req/search?service=search&request=search&version=2.0&crs=EPSG:900913&size=100&page=1&query={search_address}&type={type}&category={category}&f
`request` 라이브러리를 사용하시는 경우 `timeout`을 걸어주지 않으면, 응답을 계속해서 기다리게 됩니다.
반드시 외부 API를 호출하는 경우에는 timeout을 걸어주세요!

2021-06-28 02:01 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            search_address = request.GET.get('search_address', None)
`address`만으로 충분한 것 같습니다. 그리고 `.get()` 호출 시에 default로 None을 반환하기 때문에 적어주지 않아도 됩니다~

```suggestion
            address = request.GET.get('address')
```

2021-06-28 02:01 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            search_data = response.json()
반환되는 데이터는 어떤 형태인가요? 예시를 코멘트에 달아주실 수 있나요?

```suggestion
            search_data = response.json()
```

2021-06-28 03:19 UTC, araaaaan commented on ganadabang/settings.py
> +API_KEY    = API_KEY
넵!

2021-06-28 03:19 UTC, araaaaan commented on api/rooms/views/main.py
> +            search_address = search_address.strip()
검색시 공백제거를 위해서 썼는데 혹시 다른 방법이 있을까요?

2021-06-28 03:21 UTC, araaaaan commented on api/rooms/views/main.py
> +            return JsonResponse({'message' : 'KEY_ERROR'}, status=400)
이렇게 수정하고 싶어서 검색했었는데 안나와서... 안되나보다 했는데! 역시 멘토님....👍👍🏻👍🏼👍🏽👍🏾👍🏿
수정하겠습니다

2021-06-28 03:21 UTC, araaaaan commented on api/rooms/views/main.py
> +            response= requests.get(f'http://api.vworld.kr/req/search?service=search&request=search&version=2.0&crs=EPSG:900913&size=100&page=1&query={search_address}&type={type}&category={category}&f
넵 확인했습니다

2021-06-28 03:21 UTC, araaaaan commented on api/rooms/views/main.py
> +            search_address = request.GET.get('search_address', None)
넵!

2021-06-28 03:22 UTC, araaaaan commented on api/rooms/views/main.py
> +            search_data = response.json()
넵

2021-06-28 09:24 UTC, lordmyshepherd requested changes

2021-06-28 09:24 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            return JsonResponse({'message':'KEY_ERROR'}, status=400)
```suggestion
            if len(address) < 2 : 
                return JsonResponse({'message':'ADDRESS_IS_TOO_SHORT'}, status=400)
                
            VWORLD_URL = (f'http://api.vworld.kr/req/search?service=search&request=search&version=2.0&crs=EPSG:4326&size=100&page=1&query={address}&type={type}&category={category}&format=json&errorformat=json&key={SEARCH_API_KEY}')
            response   = requests.get(url, timeout=10).json()
            
            if not response['response']['status'] == 'OK':
                return JsonResponse({'message':'VALUE_ERROR'}, status= 400)
                
            return JsonResponse({'rooms':response['response']['result']['items']}, status=200)
            
        except KeyError:
            return JsonResponse({'message':'KEY_ERROR'}, status=400)
```

2021-06-28 09:24 UTC, lordmyshepherd commented on api/rooms/views/main.py
> +            return JsonResponse({'message':'KEY_ERROR'}, status=400)
마지막 피드백이 될 것 같습니다!

2021-06-28 10:38 UTC, araaaaan commented on api/rooms/views/main.py
> +            return JsonResponse({'message':'KEY_ERROR'}, status=400)
넵 unit test와 함께 PR 날리겠습니다~

2021-06-29 11:34 UTC, lordmyshepherd approved these changes
LGTM 👍  아란님 고생 많으셨어요~~~ 축하드려요~~

2021-06-29 11:34 UTC, lordmyshepherd commented on api/rooms/tests/test_main.py
> +    #Test 0
주석은 지워주세요~
```suggestion
    #Test 0
```

2021-06-29 11:34 UTC, merged