[김태우] Add: RoomListView 추가 완료
wecode-bootcamp-korea/21-2nd-GanadaBang-backend pull request #6
Opened 2021-06-28 00:50 UTC by jotasic

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- RoomListView 추가 완료
- 		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 현재 지도내 매물의 대한 정보를 필터링하는 View
- 쿼리스트링을 이용한 필터기능 구현
- 필터를 동일하게 사용하기 위해 데코레이터를 사용하여 분리.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 쿼리스트링 유효성 체크를 위해서 개선할 만한 사항이 더 있을까요?

**요청**
```bash
/api/rooms?filter={"roomType":[1,2,3],"tradeType":[1,2,3],"deposit":[0,200],"monthlyRent":[0,80],"sale":[0,1000000000000000000]}&location=[[126.8839788,37.4663019],[127.2238684,37.5455571]]&zoom=12
```

**응답**
```json
{
    "total": 4,
    "page": 0,
    "limit": 15,
    "next_page": 2,
    "has_more": false,
    "room_list": [
        {
            "id": 1,
            "title": "원룸1",
            "content": "매물정보 원룸 1 풀옵션 ",
            "floor": 1,
            "room_count": 1,
            "room_area": 10.12,
            "desposit": 100,
            "monthly_rent": 30,
            "sale": 0,
            "room_type": "ONE_ROOM",
            "trade_type": "MONTHLY_RENT",
            "room_image": "https://i.imgur.com/SwiHvRG.png",
            "state": "서울특별시",
            "city": "강남구",
            "dong": "삼성동",
            "location": {
                "lat": 37.50637292,
                "lng": 127.0536407
            }
        },
후략..
```

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-28 04:16 UTC, lordmyshepherd requested changes

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/tests/test_map.py
> +        RoomType.objects.create(id='3',name='OFFICETEL')
`bulk insert`를 사용하는 것이 테스트 속도를 더 높여줍니다~

```suggestion
        RoomType.objects.bulk_create([
            RoomType(id='1',name='ONE_ROOM')
            RoomType(id='2',name='MULTI_ROOM')
            RoomType(id='3',name='OFFICETEL')
        ])
```

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/tests/test_map.py
> +        TradeType.objects.create(id='3',name='SALE')
위와 마찬가지로 `bulk insert`를 사용해보세요~

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/tests/test_map.py
> +    def test_if_querry_string_is_empty(self):
테스트코드만 보고도 `/api/rooms` API를 이해하기 쉽네요!! 👍 👍 👍

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +        dong_code  = request.GET.get('dongCode')
변수명을 복수로만 수정해주시면 될 것 같아요!

```suggestion
        filters     = json.loads(request.GET.get('filter', '{}'))
        locations   = json.loads(request.GET.get('location', '[]'))
        dong_code   = request.GET.get('dongCode')
                
        room_types  = filters.get('roomType', [])
        trade_types = filters.get('tradeType', [])
```

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +    return Transformer.from_crs("epsg:5178", "epsg:4326").transform(utmk_x, utmk_y)
함수명은 동사로 만들어주세요~

```suggestion
def parse_wgs84_to_utmk(longitude, latitude):
    return Transformer.from_crs("epsg:4326", "epsg:5178").transform(latitude, longitude)

def parse_utmk_to_wgs84(utmk_x, utmk_y):
    return Transformer.from_crs("epsg:5178", "epsg:4326").transform(utmk_x, utmk_y)
```

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +def make_room_filter(func):
```suggestion
def room_filtered(func):
```

2021-06-28 04:16 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +        limit     = int(request.GET.get('limit', 15))
`offset` `limit`이 아니라 page로 받는 이유가 있을까요?
```suggestion
        next_page = 2
        has_more  = False
        page      = int(request.GET.get('page', 0))
        limit     = int(request.GET.get('limit', 15))
```

2021-06-28 04:49 UTC, jotasic commented on api/rooms/views/map.py
> +    return Transformer.from_crs("epsg:5178", "epsg:4326").transform(utmk_x, utmk_y)
수정완료하였습니다.

2021-06-28 04:49 UTC, jotasic commented on api/rooms/views/map.py
> +def make_room_filter(func):
수정완료하였습니다.

2021-06-28 04:50 UTC, jotasic commented on api/rooms/views/map.py
> +        dong_code  = request.GET.get('dongCode')
수정완료하였습니다.

2021-06-28 05:02 UTC, jotasic commented on api/rooms/tests/test_map.py
> +        RoomType.objects.create(id='3',name='OFFICETEL')
수정완료하였습니다.

2021-06-28 05:02 UTC, jotasic commented on api/rooms/tests/test_map.py
> +        TradeType.objects.create(id='3',name='SALE')
수정완료하였습니다

2021-06-28 05:02 UTC, jotasic commented on api/rooms/tests/test_map.py
> +    def test_if_querry_string_is_empty(self):
감사합니다! 👍👍👍👍👍👍

2021-06-28 05:06 UTC, jotasic commented on api/rooms/views/map.py
> +        limit     = int(request.GET.get('limit', 15))
`page` 는 몇번째 페이지인지 받을려고 하였고,
`limit` 는 한 페이지에 몇개의 결과가 있을 수 있는지 받을려고 하였는데, 지금 생각해보니 명칭이 모호한것 같습니다.

1. page, page_size 로 갈지
2. offset, limit 갈지 정해야될 것 같습니다.

2021-06-28 05:10 UTC, jotasic commented on api/rooms/views/map.py
> +        limit     = int(request.GET.get('limit', 15))
제가의도한 코드는 page, page_size 이므로 limit를 page_size으로 고치고, 추후 프론트분들과 붙여볼 시에 편하신 방식으로 수정하도록 하겠습니다.

2021-06-28 09:33 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +        limit     = int(request.GET.get('limit', 15))
해당 엔드포인트를 여러 곳에서 호출해야되는데, A화면에서는 100개, B화면에서는 10개, C서비스에서는 1000개를 받아오고 싶다고하면 이때도 페이지 number를 기준으로 받아와야 되는 문제가 생기죠!

pagination은 offset, limit으로 구현해주셔야 flexible하게 사용될 수 있습니다!

2021-06-28 10:26 UTC, jotasic commented on api/rooms/views/map.py
> +        limit     = int(request.GET.get('limit', 15))
수정완료하였습니다.

2021-06-28 22:40 UTC, lordmyshepherd commented
태우님 conflict만 수정해주시면 될 것 같아요!!

2021-06-28 22:49 UTC, lordmyshepherd requested changes
마이너한 리뷰 몇가지 남겼습니다! 확인 부탁드려도 될까요?

2021-06-28 22:49 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +        has_more  = False
page 관련 코드가 남아있는 것 같네요??

2021-06-28 22:49 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            has_more = limit <= total_count
has_more은 어떤 역할인가요??

2021-06-28 22:49 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
조회할때부터 `offset`, `limit`을 붙여주면 필요한 양만 불러올 수 있을 것 같은데 어떠신가요?
아래 has_more이 꼭 필요한 코드가 아니라면 line 78~82 코드가 없어도 될 것 같아요!

```suggestion
        rooms = Room.objects \
            .select_related('location', 'room_type', 'trade_type') \
            .prefetch_related('roomimage_set').filter(request.q)[offset:offset+limit]
```

2021-06-28 22:49 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            has_more = limit <= total_count
```suggestion
```

2021-06-28 22:49 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            'total'     : total_count,
```suggestion
            'total'     : rooms.count(),
```

2021-06-28 22:59 UTC, jotasic commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
1. 검색 조건에 해당되는 방의 총 갯수를 화면에 찍어야 되기때문에, 페지네이션 전에 전체 data의 갯수를 알아야 되서 분리하였습니다.
 - 혹시 이러한 사항때문에 분리하였는데, 다른 좋은 방법이 있으면 추천해주시면 감사하겠습니다.

2021-06-28 23:01 UTC, jotasic commented on api/rooms/views/map.py
> +            has_more = limit <= total_count
다음페이지 검색할 data가 있는지 없는지에 대한 플레그 인데, 그냥 추가한 사항입니다 따라서 아직까지는 별의미 없습니다.
(아직까지 프론트에서 사용안함)

2021-06-28 23:05 UTC, jotasic commented on api/rooms/views/map.py
> +        has_more  = False
수정완료하였습니다.

2021-06-28 23:13 UTC, jotasic commented on api/rooms/views/map.py
> +            has_more = limit <= total_count
따라서 위에 있는 next_page와 같이 삭제 진행하였습니다.

2021-06-29 03:02 UTC, lordmyshepherd requested changes

2021-06-29 03:02 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
그렇다고 하면 이경우에는 room 전체를 가져올 때, `location`, `room_type`, `trade_type` ... 전체를 같이 가져오기 때문에, 
offset, limit으로 가져오는 수를 제한하고, Room 전체 count만하는 쿼리를 추가로 날리는게 좋을 것 같아요!

2021-06-29 03:02 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
```python
total_count = Room.objects.all().count()
```

2021-06-29 03:02 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
태우님 생각은 어떠신가요?

2021-06-29 03:18 UTC, jotasic commented on api/rooms/views/map.py
> +            .prefetch_related('roomimage_set').filter(request.q)
이 경우에는 rooms 테이블에 있는 모든 데이터의 갯수를 카운팅 하기때문에 제가 생각한 의도와 다르게 동작할것 같습니다.

저는 필터링 조건에 만족하는 데이터의 전체 갯수가 몇개인지 알고 싶어서 필터 후의 카운트를 구했습니다.

2021-06-29 07:23 UTC, lordmyshepherd approved these changes
LGTM 👍👍

2021-06-29 07:23 UTC, lordmyshepherd commented on api/rooms/views/map.py
> +            'total'     : total_count,
```python
Room.objects.filter(q).count(),
```

2021-06-29 07:27 UTC, merged